export type EditableStatus = "draft" | "published";

export interface ContentEdit {
  slug: string;
  status?: EditableStatus;
  topics?: string[];
}

function sqlString(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

export function normalizeTopics(topics: string[]): string[] {
  return [...new Set(topics.map((topic) => topic.trim()).filter(Boolean))];
}

export function renderContentEditSql(edit: ContentEdit): string {
  if (edit.status === undefined && edit.topics === undefined) {
    throw new Error("At least one content field must be changed");
  }

  const statements = [
    `-- Generated by scripts/edit-content.ts for ${edit.slug}.`,
    "-- This file is temporary and must not be committed.",
  ];

  const updates = ["updated_at = CURRENT_TIMESTAMP"];
  if (edit.status !== undefined) {
    updates.unshift(`status = ${sqlString(edit.status)}`);
  }
  statements.push(
    `UPDATE posts SET ${updates.join(", ")} WHERE slug = ${sqlString(edit.slug)};`,
  );

  if (edit.topics !== undefined) {
    const topics = normalizeTopics(edit.topics);
    for (const topic of topics) {
      statements.push(
        `INSERT INTO topics (name, slug) VALUES (${sqlString(topic)}, ${sqlString(topic)}) ON CONFLICT (name) DO UPDATE SET slug = excluded.slug WHERE topics.slug IS NOT excluded.slug;`,
      );
    }
    statements.push(
      `DELETE FROM post_topics WHERE post_id = (SELECT id FROM posts WHERE slug = ${sqlString(edit.slug)});`,
    );
    for (const topic of topics) {
      statements.push(
        `INSERT OR IGNORE INTO post_topics (post_id, topic_id) SELECT p.id, t.id FROM posts AS p CROSS JOIN topics AS t WHERE p.slug = ${sqlString(edit.slug)} AND t.name = ${sqlString(topic)};`,
      );
    }
    statements.push(
      "DELETE FROM topics WHERE id NOT IN (SELECT topic_id FROM post_topics);",
    );
  }

  return `${statements.join("\n")}\n`;
}
