#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";

interface Frontmatter {
  title: string;
  date: string;
  description: string;
  excerpt: string;
  categories?: string[];
  tags?: string[];
  lastUpdated?: string;
  contentHash: string;
}

const projectRoot = process.cwd();
const contentDirectory = path.join(projectRoot, "content", "blog");
const defaultOutput = path.join(
  projectRoot,
  "apps",
  "api",
  "migrations",
  "0002_seed_content.sql",
);

function sqlString(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function requiredString(
  value: unknown,
  field: string,
  fileName: string,
): string {
  if (typeof value !== "string" || !value) {
    throw new Error(`${fileName}: ${field} is required`);
  }
  return value;
}

function readPosts(): Array<Frontmatter & { slug: string }> {
  return fs
    .readdirSync(contentDirectory)
    .filter((fileName) => fileName.endsWith(".mdx"))
    .sort()
    .map((fileName) => {
      const slug = fileName.replace(/\.mdx$/, "");
      const filePath = path.join(contentDirectory, fileName);
      const { data } = matter(fs.readFileSync(filePath, "utf8"));
      const frontmatter = data as Partial<Frontmatter>;

      return {
        slug,
        title: requiredString(frontmatter.title, "title", fileName),
        date: requiredString(frontmatter.date, "date", fileName),
        description: requiredString(
          frontmatter.description,
          "description",
          fileName,
        ),
        excerpt: requiredString(frontmatter.excerpt, "excerpt", fileName),
        categories: frontmatter.categories ?? [],
        tags: frontmatter.tags ?? [],
        lastUpdated: frontmatter.lastUpdated,
        contentHash: requiredString(
          frontmatter.contentHash,
          "contentHash",
          fileName,
        ),
      };
    });
}

function render(posts: Array<Frontmatter & { slug: string }>): string {
  const topics = new Set<string>();
  for (const post of posts) {
    for (const topic of [...(post.categories ?? []), ...(post.tags ?? [])]) {
      topics.add(topic);
    }
  }

  const lines = [
    "-- Generated by scripts/export-content-sql.ts.",
    "-- This is the initial import from the Git-managed MDX metadata.",
    "BEGIN TRANSACTION;",
  ];

  for (const post of posts) {
    const status = post.slug.startsWith("test-") ? "draft" : "published";
    lines.push(
      `INSERT INTO posts (slug, title, date, description, excerpt, last_updated, content_hash, content_path, status) VALUES (${sqlString(post.slug)}, ${sqlString(post.title)}, ${sqlString(post.date)}, ${sqlString(post.description)}, ${sqlString(post.excerpt)}, ${post.lastUpdated ? sqlString(post.lastUpdated) : "NULL"}, ${sqlString(post.contentHash)}, ${sqlString(`content/blog/${post.slug}.mdx`)}, ${sqlString(status)}) ON CONFLICT (slug) DO UPDATE SET title = excluded.title, date = excluded.date, description = excluded.description, excerpt = excluded.excerpt, last_updated = excluded.last_updated, content_hash = excluded.content_hash, content_path = excluded.content_path, status = excluded.status, updated_at = CURRENT_TIMESTAMP;`,
    );
    lines.push(
      `DELETE FROM post_topics WHERE post_id = (SELECT id FROM posts WHERE slug = ${sqlString(post.slug)});`,
    );
  }

  for (const topic of [...topics].sort()) {
    lines.push(
      `INSERT INTO topics (name, slug) VALUES (${sqlString(topic)}, ${sqlString(topic)}) ON CONFLICT (name) DO UPDATE SET slug = excluded.slug;`,
    );
  }

  for (const post of posts) {
    const postTopics = new Set([
      ...(post.categories ?? []),
      ...(post.tags ?? []),
    ]);
    for (const topic of postTopics) {
      lines.push(
        `INSERT OR IGNORE INTO post_topics (post_id, topic_id) SELECT p.id, t.id FROM posts AS p CROSS JOIN topics AS t WHERE p.slug = ${sqlString(post.slug)} AND t.name = ${sqlString(topic)};`,
      );
    }
  }

  lines.push("COMMIT;", "");
  return lines.join("\n");
}

function main(): void {
  const outputIndex = process.argv.indexOf("--output");
  const outputPath =
    outputIndex >= 0 ? process.argv[outputIndex + 1] : defaultOutput;
  if (!outputPath) throw new Error("--output requires a file path");

  const absolutePath = path.resolve(projectRoot, outputPath);
  fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
  fs.writeFileSync(absolutePath, render(readPosts()), "utf8");
  console.log(
    `Wrote D1 seed SQL to ${path.relative(projectRoot, absolutePath)}`,
  );
}

main();
